version: '3.7'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testdb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
